// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsTeamExample;

namespace SportsTeamExample.Migrations
{
    [DbContext(typeof(SportsTeamContext))]
    partial class SportsTeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsTeamExample.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LeBron James",
                            Number = 6,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bugs Bunny",
                            Number = 10,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Devin Booker",
                            Number = 13,
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("SportsTeamExample.Models.PlayerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PositionId");

                    b.ToTable("PlayerPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            PlayerId = 1,
                            PositionId = 3
                        },
                        new
                        {
                            Id = 3,
                            PlayerId = 3,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 4,
                            PlayerId = 2,
                            PositionId = 4
                        },
                        new
                        {
                            Id = 5,
                            PlayerId = 2,
                            PositionId = 3
                        });
                });

            modelBuilder.Entity("SportsTeamExample.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Point Guard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shooting Guard"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Small Forward"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Power Forward"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Center"
                        });
                });

            modelBuilder.Entity("SportsTeamExample.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tune World",
                            Name = "Tune Squad"
                        },
                        new
                        {
                            Id = 2,
                            City = "Phoenix",
                            Name = "Suns"
                        });
                });

            modelBuilder.Entity("SportsTeamExample.Models.Player", b =>
                {
                    b.HasOne("SportsTeamExample.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportsTeamExample.Models.PlayerPosition", b =>
                {
                    b.HasOne("SportsTeamExample.Models.Player", "Player")
                        .WithMany("Positions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsTeamExample.Models.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SportsTeamExample.Models.Player", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("SportsTeamExample.Models.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("SportsTeamExample.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
